Была создана основа backend, были подключены swagger и взаимодействие…
haniichees/news-portal pull request #6
Opened 2020-07-09 16:08 UTC by iBurakov33

… с PostgreSQL

2020-07-10 06:49 UTC, OlegOvsienko requested changes

2020-07-10 06:49 UTC, OlegOvsienko commented on server/NewsPortalWebApi/Controllers/NewsController.cs
> +        public async Task<IActionResult> PutNews(int id, News news)
в качестве идентификатора лучше использовать GUID

2020-07-10 06:49 UTC, OlegOvsienko commented on server/NewsPortalWebApi/Controllers/NewsController.cs
> +        public async Task<IActionResult> PutNews(int id, News news)
и объедините параметры в 1 модель News, зачем идентификатор сущности отдельно?

2020-07-10 06:49 UTC, OlegOvsienko commented on server/NewsPortalWebApi/Controllers/NewsController.cs
> +            }
не пойму зачем это

2020-07-10 06:49 UTC, OlegOvsienko commented on server/NewsPortalWebApi/Controllers/NewsController.cs
> +            _context.Entry(news).State = EntityState.Modified;
страшная конструкция
по идее что нужно сделать:
- получить модель с БД
-  обновить данные
- сохранить изменения

2020-07-10 06:49 UTC, OlegOvsienko commented on server/NewsPortalWebApi/Controllers/NewsController.cs
> +            _context.News.Add(news);
логика в контроллерах
скидывал же вчера про n-layer и паттерн репозиторий
не вижу)

2020-07-10 06:49 UTC, OlegOvsienko commented on server/NewsPortalWebApi/Controllers/NewsController.cs
> +            _context.News.Add(news);
контроллер отвечает только за часть представления
в нем не должно быть бизнес логики

2020-07-10 06:49 UTC, OlegOvsienko commented on server/NewsPortalWebApi/Controllers/NewsController.cs
> +            _context.News.Add(news);
также рекомендую использовать паттерн DTO
https://www.codeproject.com/Articles/1050468/Data-Transfer-Object-Design-Pattern-in-Csharp
для чего нужен, у вас будут различаться модели для фронта и модели для хранения данных в БД
к примеру могут быть доп поля, статусы, даты создания и пр.

2020-07-10 06:49 UTC, OlegOvsienko commented on server/NewsPortalWebApi/Controllers/NewsController.cs
> +            _context.News.Add(news);
для перегонки моделей обычно используется automapper
https://automapper.org/

2020-07-10 06:49 UTC, OlegOvsienko commented on server/NewsPortalWebApi/Data/IEntity.cs
> +    public interface IEntity
интерфейс следует выделять для классов с BL, репозиториев.
зачем интерфейс для анемичной модели?
это ерунда

2020-07-10 06:49 UTC, OlegOvsienko commented on server/NewsPortalWebApi/Models/News.cs
> +        public int Id { get; set; }
не хватает еще основного текста новости
+ можно добавить всякую мета информация
например флаг актуальность, чтоб можно было скрывать новости
дату создания, дату изменения
еще что-то

2020-07-10 06:49 UTC, OlegOvsienko commented on server/NewsPortalWebApi/Models/News.cs
> +        public string NewsImage { get; set; }
картинка строкой - приколько)
следует использовать тип byte[]

2020-07-11 06:00 UTC, Mixaon commented on server/NewsPortalWebApi/Models/News.cs
> +        public string NewsImage { get; set; }
В этом поле будет содержаться путь к картинке в файловой системе

2020-07-13 10:08 UTC, closed without merging